const express=require('express');const fs=require('fs');const path=require('path');const vm=require('vm');
const app=express();const PORT=process.env.PORT||3000;const OLLAMA_URL=process.env.OLLAMA_URL||'http://127.0.0.1:11434';const OLLAMA_MODEL=process.env.OLLAMA_MODEL||'gemma4:e2b';
const part=fs.readFileSync(path.join(__dirname,'data/quotes-part1.js'),'utf8');const ctx={};vm.createContext(ctx);vm.runInContext(part+';this.__quotes=quotesPart1;',ctx);const quotes=ctx.__quotes;
app.use(express.json({limit:'100kb'}));app.use(express.static(__dirname));
async function callOllama(prompt){const r=await fetch(`${OLLAMA_URL}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:OLLAMA_MODEL,prompt,stream:false,format:'json'})});if(!r.ok)throw new Error(`Ollama ${r.status}`);const d=await r.json();return JSON.parse(d.response)}
function terms(v){if(!v)return[];if(Array.isArray(v))return v.map(String);return String(v).split(/[\s,\/·]+/).filter(Boolean)}
function score(q,a,input){const h=[...(q.categories||[]),...(q.emotions||[]),q.meaning||'',q.action||'',q.translation||''].join(' ').toLowerCase();const ts=[...terms(a.emotion),...terms(a.situation),...terms(a.theme),...terms(a.keywords),...terms(input)].map(x=>x.toLowerCase());let s=0;for(const t of ts){if(t.length<2)continue;if((q.emotions||[]).some(x=>String(x).includes(t)||t.includes(String(x))))s+=6;if((q.categories||[]).some(x=>String(x).includes(t)||t.includes(String(x))))s+=5;if(h.includes(t))s+=2}return s}
app.post('/api/recommend',async(req,res)=>{const text=String(req.body?.text||'').trim();const recentIds=Array.isArray(req.body?.recentIds)?req.body.recentIds.map(Number):[];if(!text)return res.status(400).json({error:'text is required'});try{const analysis=await callOllama(`당신은 한국어 감정/상황 분석기다. JSON만 반환한다. 스키마: {"emotion":"대표 감정 1개","situation":"상황 2~6단어","theme":"필요한 메시지 주제 1~2개","keywords":["검색 키워드 최대 5개"]}\n사용자 문장:\n${text}`);let available=quotes.filter(q=>!recentIds.includes(q.id));if(available.length<5)available=quotes;let ranked=available.map(q=>({q,score:score(q,analysis,text)})).sort((a,b)=>b.score-a.score);let candidates=ranked.slice(0,5).map(x=>x.q);if(!candidates.length||ranked[0]?.score===0)candidates=available.sort(()=>Math.random()-.5).slice(0,5);const compact=candidates.map(q=>({id:q.id,quote:q.quote,translation:q.translation,categories:q.categories,emotions:q.emotions,meaning:q.meaning}));const choice=await callOllama(`당신은 명언 추천 어시스턴트다. 후보 중 가장 적합한 quoteId 하나만 선택하고 새 명언을 만들지 마라. JSON 스키마: {"quoteId":숫자,"reason":"한국어 1~2문장","action":"오늘 바로 할 작은 행동 1문장"}\n사용자:${text}\n분석:${JSON.stringify(analysis)}\n후보:${JSON.stringify(compact)}`);if(!candidates.some(q=>q.id===Number(choice.quoteId)))choice.quoteId=candidates[0].id;res.json({emotion:analysis.emotion||'현재 감정',situation:analysis.situation||'',theme:analysis.theme||'추천',keywords:analysis.keywords||[],quoteId:Number(choice.quoteId),reason:choice.reason||candidates[0].meaning,action:choice.action||candidates[0].action})}catch(e){console.error(e);res.status(502).json({error:'ollama_unavailable',detail:e.message})}});
app.listen(PORT,()=>{console.log(`Quote app: http://localhost:${PORT}`);console.log(`Ollama model: ${OLLAMA_MODEL}`)});
